---
- name: Ensure Python3, pip, and base packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - firewalld
      - net-tools
      - apt-utils
    state: present
    update_cache: true

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Check if Docker repo exists
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo_file

- name: Add Docker repository if missing
  ansible.builtin.shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg
    | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: not docker_repo_file.stat.exists

- name: Set up Docker repository
  ansible.builtin.shell: >
    echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
    https://download.docker.com/linux/ubuntu jammy stable" |
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: not docker_repo_file.stat.exists

- name: Install Docker Engine and Docker Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: true
