---
# Ensure base packages
- name: Ensure Python3, pip, and base packages are installed
  dnf:
    name:
      - python3
      - python3-pip
      - firewalld
      - net-tools
      - yum-utils  # needed for repo management
    state: present

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: true

# Check if Docker CE repo already exists
- name: Check if Docker CE repo exists
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo_file

# Add Docker CE repo if missing
- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: not docker_repo_file.stat.exists

# Ensure Python Docker SDK is present
- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

# Install Docker CE and plugins
- name: Install Docker CE and plugins
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    enablerepo: docker-ce-stable

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true

