---
- name: Create Wazuh network
  community.docker.docker_network:
    name: wazuh-net

- name: Ensure Wazuh Manager container is running
  community.docker.docker_container:
    name: wazuh-manager
    image: wazuh/wazuh-manager:4.7.3
    platform: linux/amd64
    state: started
    restart_policy: always
    networks:
      - name: wazuh-net
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - /var/ossec/data:/var/ossec/data

#Firewall rules
- name: Allow 55000/tcp only from Nginx
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ nginx_private_ip }}" port protocol="tcp" port="55000" accept'
    permanent: yes
    state: enabled

- name: Allow 1514/udp + 1515/tcp from any agent
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 1514/udp
    - 1515/tcp

- name: Reload firewalld
  command: firewall-cmd --reload
