---
- name: Deploy Nexus container
  community.docker.docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    restart_policy: always
    ports:
      - "8081:8081"
    env:
      INSTALL4J_ADD_VM_PARAMS: "-Xms512m -Xmx1024m"
    volumes:
      - nexus-data:/nexus-data
