---
- name: Create Wazuh network
  community.docker.docker_network:
    name: wazuh-net

- name: Ensure Wazuh Manager container is running
  community.docker.docker_container:
    name: wazuh-manager
    image: wazuh/wazuh-manager:4.7.3
    platform: linux/amd64
    state: started
    restart_policy: always
    networks:
      - name: wazuh-net
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - /var/ossec/data:/var/ossec/data

- name: Ensure Wazuh Dashboard container is running
  community.docker.docker_container:
    name: wazuh-dashboard
    image: wazuh/wazuh-dashboard:4.7.3
    platform: linux/amd64
    state: started
    restart_policy: always
    networks:
      - name: wazuh-net
    ports:
      - "5601:5601"
    env:
      WAZUH_API_URL: "https://wazuh-manager:55000"
      WAZUH_API_USER: "admin"
      WAZUH_API_PASSWORD: "SecretPassword"
      WAZUH_INDEXER_URL: "https://10.0.2.108:9200"
