---
- name: Install Docker and Compose
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Create Wazuh project directory
  file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Stop and remove old Wazuh containers and volumes
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: absent
    remove_volumes: true
    remove_images: all
  ignore_errors: true
  become: true

- name: Deploy Wazuh Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    force: true
  notify: Deploy Wazuh stack with Docker Compose v2
  become: true

- name: Deploy Wazuh stack with Docker Compose v2
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    remove_orphans: true
    pull: always
  become: true

- name: Allow Wazuh Indexer (9200) from Wazuh VM
  firewalld:
    rich_rule: >
      rule family="ipv4"
      source address="{{ wazuh_private_ip }}"
      port protocol="tcp" port="9200" accept
    permanent: true
    state: enabled
  become: true

- name: Allow Wazuh Dashboard (5601) from Nginx
  firewalld:
    rich_rule: >
      rule family="ipv4"
      source address="{{ nginx_private_ip }}"
      port protocol="tcp" port="5601" accept
    permanent: true
    state: enabled
  become: true

- name: Allow Wazuh API (55000) from Nginx
  firewalld:
    rich_rule: >
      rule family="ipv4"
      source address="{{ nginx_private_ip }}"
      port protocol="tcp" port="55000" accept
    permanent: true
    state: enabled
  become: true

- name: Allow agents to connect (1514/udp, 1515/tcp)
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 1514/udp
    - 1515/tcp
  become: true
