---
nginx_domain: desdevsecops.duckdns.org

nginx_public_ip: 63.145.32.171
nginx_private_ip: 1.0.1.100
wazuh_private_ip: 1.0.2.36
wazuh_indexer_host: 1.0.2.59
nexus_private_ip: 1.0.2.8
tomcat_private_ip: 127.0.0.1
wireguard_private_ip: 
# Nginx landing page
nginx_auth_user: nginxadmin
nginx_auth_password: "Secure#proxy_123"

# Wazuh Dashboard
wazuh_auth_user: wazuhadmin
wazuh_auth_password: "Secure#proxy_wazuh123"

# Nexus Repository
nexus_auth_user: nexusadmin
nexus_auth_password: "AnotherSecret#456_nexus"

# Tomcat Manager
tomcat_auth_user: tomcatadmin
tomcat_auth_password: "Super#Tomcat123_tomcat"

nginx_users:
  - { name: "{{ nginx_auth_user }}",  password: "{{ nginx_auth_password }}",  file: "/etc/nginx/.htpasswd_nginx" }
  - { name: "{{ nexus_auth_user }}",  password: "{{ nexus_auth_password }}",  file: "/etc/nginx/.htpasswd_nexus" }
  - { name: "{{ wazuh_auth_user }}",  password: "{{ wazuh_auth_password }}",  file: "/etc/nginx/.htpasswd_wazuh" }
  - { name: "{{ tomcat_auth_user }}", password: "{{ tomcat_auth_password }}", file: "/etc/nginx/.htpasswd_tomcat" }


