---
- name: Deploy WireGuard container with Docker
  community.docker.docker_container:
    name: wireguard
    image: linuxserver/wireguard:latest
    state: started
    restart_policy: always
    privileged: true
    volumes:
      - /etc/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    capabilities:
      - NET_ADMIN
