---
- name: Deploy WireGuard container
  community.docker.docker_container:
    name: wireguard
    image: linuxserver/wireguard
    state: started
    restart_policy: always
    ports:
      - "51820:51820/udp"
    volumes:
      - /etc/wireguard:/config
      - /lib/modules:/lib/modules
