---
- name: Ensure WireGuard config directory exists
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Deploy WireGuard config file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'

# Check if community.docker is installed
- name: Check if community.docker collection is available
  command: ansible-galaxy collection list community.docker
  register: docker_collection_check
  ignore_errors: true
  delegate_to: localhost
  changed_when: false
  run_once: true

- name: Set fact if docker_collection_available
  set_fact:
    docker_collection_available: "{{ 'community.docker' in docker_collection_check.stdout }}"

# Preferred: Use community.docker if available
- name: Deploy WireGuard container with community.docker
  community.docker.docker_container:
    name: wireguard
    image: linuxserver/wireguard:latest
    state: started
    restart_policy: always
    privileged: true
    volumes:
      - /etc/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    capabilities:
      - NET_ADMIN
  when: docker_collection_available

# Fallback: Use raw docker run if community.docker missing
- name: Deploy WireGuard container with raw docker run
  command: >
    docker run -d
    --name wireguard
    --restart always
    --privileged
    -v /etc/wireguard:/config
    -v /lib/modules:/lib/modules
    -p 51820:51820/udp
    --cap-add=NET_ADMIN
    linuxserver/wireguard:latest
  args:
    creates: /var/lib/docker/containers
  when: not docker_collection_available
