---
- name: Create certs directory
  file:
    path: /etc/nginx/certs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy self-signed cert
  copy:
    src: files/certs/selfsigned.crt
    dest: /etc/nginx/certs/selfsigned.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy self-signed key
  copy:
    src: files/certs/selfsigned.key
    dest: /etc/nginx/certs/selfsigned.key
    owner: root
    group: root
    mode: '0600'

- name: Copy reverse proxy config
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'

- name: Deploy Nginx container
  docker_container:
    name: nginx
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    restart_policy: always
