all:
  vars:
    ansible_user: opc
    ansible_ssh_private_key_file: ~/.ssh/oci_api_key.pem
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true

  children:
    public:
      hosts:
        publicvm:
          ansible_host: "{{ nginx_private_ip }}"

    private:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p opc@{{ nginx_public_ip }} -i ~/.ssh/oci_api_key.pem"

      hosts:
        wazuhvm:
          ansible_host: "{{ wazuh_private_ip }}"
        elasticvm:
          ansible_host: "{{ wazuh_indexer_host }}"
        nexusvm:
          ansible_host: "{{ nexus_private_ip }}"
