---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/oci_api_key.pem
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true

  children:
    public:
      hosts:
        publicvm:
          ansible_host: "{{ nginx_public_ip }}"

    private:
      vars:
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ nginx_public_ip }} -i ~/.ssh/oci_api_key.pem"

      children:
        wazuh:
          hosts:
            wazuhvm:
              ansible_host: "{{ wazuh_private_ip }}"

        nexus:
          hosts:
            nexusvm:
              ansible_host: "{{ nexus_private_ip }}"

        wireguard:
          hosts:
            wireguardvm:
              ansible_host: "{{ wireguard_private_ip }}"
