---
all:
  children:
    public:
      hosts:
        publicvm:
          ansible_host: "{{ nginx_public_ip }}"

  vars:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ~/.ssh/oci_api_key.pem
  ansible_python_interpreter: /usr/bin/python3
  ansible_become: true
  ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ nginx_public_ip }} -i ~/.ssh/oci_api_key.pem"'

    # private:
    #   vars:
    #     ansible_ssh_common_args: >-
    #       -o ProxyCommand="ssh -W %h:%p ubuntu@{{ nginx_public_ip }} -i ~/.ssh/oci_api_key.pem"

    #   hosts:
    #     wazuhvm:
    #       ansible_host: "{{ wazuh_private_ip }}"
    #     elasticvm:
    #       ansible_host: "{{ wazuh_indexer_host }}"
    #     nexusvm:
    #       ansible_host: "{{ nexus_private_ip }}"
