---
- hosts: all
  roles:
    - common

- hosts: publicvm
  roles:
    - nginx
    - tomcat

- hosts: wazuh
  roles:
    - wazuh

- hosts: nexus
  roles:
    - nexus

- hosts: wireguard
  roles:
    - wireguard

# - name: Common setup across all VMs
#   hosts: all
#   become: true
#   roles:
#     - common

# - name: Setup Public VM
#   hosts: public
#   become: true
#   gather_facts: false
#   tasks:
#     - import_tasks: roles/common/tasks/public.yml
#   roles:
#     - nginx
#     - tomcat

# - hosts: wazuh_manager
#   become: yes
#   gather_facts: false
#   roles:
#     - role: wazuh-manager
#     - role: wazuh-dashboard

# - name: Setup Elasticsearch VM
#   hosts: elasticvm
#   become: true
#   gather_facts: false
#   roles:
#     - elasticsearch

# - name: Setup Nexus VM
#   hosts: nexusvm
#   become: true
#   roles:
#     - nexus
