---
- name: Common setup across all VMs
  hosts: all
  become: true
  roles:
    - common

- name: Setup Public VM
  hosts: public
  become: true
  tasks:
    - import_tasks: roles/common/tasks/public.yml
  roles:
    - nginx
    - wireguard
    - tomcat

- name: Setup Wazuh VM
  hosts: wazuhvm
  become: true
  roles:
    - wazuh

- name: Setup Elasticsearch VM
  hosts: elasticvm
  become: true
  roles:
    - elasticsearch

- name: Setup Nexus VM
  hosts: nexusvm
  become: true
  roles:
    - nexus
