---
- name: Common setup across all VMs
  hosts: all
  become: true
  roles:
    - common

- name: Setup Public VM
  hosts: public
  become: true
  roles:
    - nginx
    - tomcat

- name: Setup Wazuh VM
  hosts: wazuhvm
  become: true
  roles:
    - wazuh

- name: Setup Nexus VM
  hosts: nexusvm
  become: true
  roles:
    - nexus

- name: Setup WireGuard VM
  hosts: wireguardvm
  become: true
  roles:
    - wireguard
