---
- name: Deploy Wazuh stack with Docker Compose v2
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    remove_orphans: true
    pull: always
  become: true
